theme = "base16_transparent"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.indent-guides]
# render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
C-o = ":open ~/.config/helix/config.toml"
C-r = ":config-reload"

[keys.normal]
A-tab = ":buffer-next"
A-S-tab = ":buffer-previous"

A-j = "half_page_down"
A-k = "half_page_up"
A-w = ":buffer-close"
A-p = "buffer_picker"


[keys.normal.g]
G = "goto_file_end"
