#! /bin/sh

pgrep sxhkd || sxhkd &
setxkbmap -layout us,ru
~/bin/bls -w
~/bin/rofi/enable\ tapping
~/bin/rofi/disable\ touchscreen

bspc monitor -d 1 2 3 4 5 6 7 8 9

pgrep blockbar || blockbar ~/.config/blockbar/blb &

xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n blockbar)

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding       50

pgrep ws || ~/.config/bspwm/ws --daemon &

function pactl_loop {
    ~/.config/bspwm/pulsen | while read line; do
        bbc-ping-by-name vol;
    done
}

pactl_loop &

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Chromium desktop='^1' follow=on
#bspc rule -a TelegramDesktop desktop='^4'
