#! /bin/sh

pgrep sxhkd || sxhkd &
setxkbmap -layout us,ru
~/bin/bls -w

bspc monitor -d 1 2 3 4 5 6 7 8 9

pgrep blockbar || blockbar ~/.config/blockbar/blockbar.json &

xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n blockbar)

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding       50

function workspace_loop {
    bspc subscribe | while read line; do
        ~/.config/blockbar/workspaces -- from bspwmrc;
    done
}

PACTL_EXACT_CALLS_NUMBER=2

function pactl_loop {                                             
    pulseaudio -k
    sleep 2
    pulseaudio -D

    self_last_client=''
    pactl subscribe | while read line; do
        current_client=$(echo $line | rg -o "client #([0-9]+)" -r '$1')
        if [[ "$self_last_client" -lt "$current_client" ]]
        then
            self_last_client=$(expr $current_client + $PACTL_EXACT_CALLS_NUMBER);
            bbc exec $(bbc list | grep vol | awk '{print $1}');
        fi
    done
}

workspace_loop &
pactl_loop &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'

