#!/bin/sh
stat=$(acpi)
perc=$(echo $stat | rg -o "([0-9]+)%" -r '$1')

case $perc in
    [0-9])
        glyph=''
        color='#FF8060'
        ;;
    1[0-9])
        glyph=''
        color='#909060'
        ;;
    2[0-9])
        glyph=''
        color='#80A060'
        ;;
    3[0-9])
        glyph=''
        color='#70E070'
        ;;
    4[0-9])
        glyph=''
        color='#70E080'
        ;;
    5[0-9])
        glyph=''
        color='#70E080'
        ;;
    6[0-9])
        glyph=''
        color='#70E0A0'
        ;;
    7[0-9])
        glyph=''
        color='#70E0A0'
        ;;
    8[0-9])
        glyph=''
        color='#70E0A0'
        ;;
    9[0-9])
        glyph=''
        color='#70E0B0'
        ;;
    100)
        glyph=''
        color='#70E0B0'
        ;;
esac


if echo $stat | rg "Charging" > /dev/null;
then
    glyph=''
    color='#70D0B0';
fi

printf "%s %s\n" $glyph $perc
printf "%s %s\n" $glyph $perc
printf "%s" $color

