#!/bin/sh

if pgrep pulseaudio > /dev/null;
then
    vol=$(ponymix get-volume)
    if ponymix is-muted;
    then
        printf "婢 %s\n" "$vol"
        printf "婢 %s\n" "$vol"
        echo '#606060'
    else
        printf "墳 %s\n" $vol
        printf "墳 %s\n" $vol
        echo '#ff66cc'
    fi
else
    printf "^v-----"
fi

