#!/bin/sh

function barf {
    printf $@
    printf $@
}

if [[ ! -z "$(ip link show | grep enp0)" ]]
then
    if [[ ! -z "$(ip link show | grep POINTOPOINT)" ]]
    then
        barf '\n'
        printf '#30F098'
    else
        barf '\n'
        printf '#5080A0'
    fi
else
    barf '\n'
    printf '#808080'
fi

