#!/bin/python
import os
import json
from bb import bspc, BAR_OUTPUT, BLOCK_BUTTON, SUBBLOCK

colFocused = '#AA4488'
colUnfocused = '#243236'
colUrgent = '#632627'


if (BLOCK_BUTTON == "1" and SUBBLOCK != ""):
    blk_idx = int(SUBBLOCK) + 1
    state = bspc('subscribe -c 1')
    idx = 0
    ws_num = 0
    for ws in state.split(':')[1:]:
        ws_num += 1
        if ws[0] in 'FoOuU':
            idx += 1
        if idx == blk_idx:
            bspc(f'desktop -f {BAR_OUTPUT}:^{ws_num}')
            break

if BLOCK_BUTTON in ['4', '5']:
    if BLOCK_BUTTON == '4':
        os.system("bspc desktop -f '" + BAR_OUTPUT + ":focused#prev.occupied'")
    elif BLOCK_BUTTON == '5':
        os.system("bspc desktop -f '" + BAR_OUTPUT + ":focused#next.occupied'")

subblocks = []

report = bspc('subscribe -c 1')
BSPWM_DISPLAY = report.split(':')[0][2:]

visible_blk_idx = 0
# first entry is monitor name, I'll make use of it one day. Maybe.
for opt in report.split(':')[1:]:
    opt_type = opt[0]
    workspace = opt[1:]

    if opt_type == 'f':
        continue
    elif opt_type == 'o':
        col = colUnfocused
    elif opt_type in ['O', 'F', 'U']:
        col = colFocused
    elif opt_type == 'u':
        col = colUrgent

    else:
        break

    block = {'text': workspace,
             'background': col,
             'bgxpad': 11,
             'bgrad': 3,
             'bgypad': 2,
             'margin': 2
            }

    subblocks.append(block)

final_data = json.dumps({'subblocks': subblocks})
# detect if script was executed by blockbar,
# assuming eachmon is set to true for this block and this block has index 1
if BAR_OUTPUT:
    print(final_data)
else:
    os.system(f'bbc property 1:{BSPWM_DISPLAY} execdata \'{final_data}\'')
