#!/bin/sh
xinput set-prop `xinput list | grep "ELAN Touchscreen" | sed -r 's/([^0-9]*([0-9]*)){1}.*/\2/'` `xinput list-props \`xinput list | grep "ELAN Touchscreen" | sed -r 's/([^0-9]*([0-9]*)){1}.*/\2/'\` | grep "Device Enabled" | head -1 | sed -r 's/([^0-9]*([0-9]*)){1}.*/\2/'` 0

